In [3]:
print("hello")

hello

In [4]:
!pip install numpy
!pip install pandas
!pip install matplotlib
!pip install seaborn
!pip install scikit-learn

Requirement already satisfied: numpy in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (2.4.5)

[notice] A new release of pip is available: 25.1.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from pandas) (2.4.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: matplotlib in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from matplotlib) (2.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: seaborn in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from seaborn) (2.4.5)
Requirement already satisfied: pandas>=1.2 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from seaborn) (3.0.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from seaborn) (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=8 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: scikit-learn in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from scikit-learn) (2.4.5)
Requirement already satisfied: scipy>=1.10.0 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\cansu\pycharmprojects\nasa_tubofan_engine_pdm\.venv\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.1.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import r2_score

In [6]:
path="C:\\Users\\CANSU\\Desktop\\ML\\NASA TURBOFAN DATASET\\train_FD001.txt"
df=pd.read_csv(path,sep=" ")

In [7]:
df.head()

,1,1.1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,8138.62,8.4195,0.03,392,2388,100.00,39.06,23.4190,Unnamed: 26,Unnamed: 27
0,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236,NaN,NaN
1,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442,NaN,NaN
2,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739,NaN,NaN
3,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044,NaN,NaN
4,1,6,-0.0043,-0.0001,100.0,518.67,642.10,1584.47,1398.37,14.62,...,8132.85,8.4108,0.03,391,2388,100.0,38.98,23.3669,NaN,NaN

In [8]:
df.shape

(20630, 28)

In [9]:
df.columns

Index(['1', '1.1', '-0.0007', '-0.0004', '100.0', '518.67', '641.82',
       '1589.70', '1400.60', '14.62', '21.61', '554.36', '2388.06', '9046.19',
       '1.30', '47.47', '521.66', '2388.02', '8138.62', '8.4195', '0.03',
       '392', '2388', '100.00', '39.06', '23.4190', 'Unnamed: 26',
       'Unnamed: 27'],
      dtype='str')

In [10]:
df.drop(['Unnamed: 27','Unnamed: 26'],axis=1,inplace=True) # I am dropping features that has just NaN value

In [11]:
df.columns

Index(['1', '1.1', '-0.0007', '-0.0004', '100.0', '518.67', '641.82',
       '1589.70', '1400.60', '14.62', '21.61', '554.36', '2388.06', '9046.19',
       '1.30', '47.47', '521.66', '2388.02', '8138.62', '8.4195', '0.03',
       '392', '2388', '100.00', '39.06', '23.4190'],
      dtype='str')

In [14]:
columns_name=["unit_number","time_in_cycles","os_1","os_2","os_3"]
for i in range(1,22):
    columns_name.append(f"s_{i}")
columns_name

['unit_number',
 'time_in_cycles',
 'os_1',
 'os_2',
 'os_3',
 's_1',
 's_2',
 's_3',
 's_4',
 's_5',
 's_6',
 's_7',
 's_8',
 's_9',
 's_10',
 's_11',
 's_12',
 's_13',
 's_14',
 's_15',
 's_16',
 's_17',
 's_18',
 's_19',
 's_20',
 's_21']

In [15]:
df.columns=columns_name
df.head()

,unit_number,time_in_cycles,os_1,os_2,os_3,s_1,s_2,s_3,s_4,s_5,...,s_12,s_13,s_14,s_15,s_16,s_17,s_18,s_19,s_20,s_21
0,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
1,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
2,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
3,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044
4,1,6,-0.0043,-0.0001,100.0,518.67,642.10,1584.47,1398.37,14.62,...,521.68,2388.03,8132.85,8.4108,0.03,391,2388,100.0,38.98,23.3669

In [22]:
df.isna().sum()

unit_number       0
time_in_cycles    0
os_1              0
os_2              0
os_3              0
s_1               0
s_2               0
s_3               0
s_4               0
s_5               0
s_6               0
s_7               0
s_8               0
s_9               0
s_10              0
s_11              0
s_12              0
s_13              0
s_14              0
s_15              0
s_16              0
s_17              0
s_18              0
s_19              0
s_20              0
s_21              0
dtype: int64

In [25]:
for col in df.columns:
    print(df[col].value_counts())

unit_number
69    362
92    341
96    336
67    313
83    293
     ...
58    147
57    137
70    137
91    135
39    128
Name: count, Length: 100, dtype: int64
time_in_cycles
2      100
3      100
4      100
5      100
6      100
      ...
358      1
359      1
360      1
361      1
362      1
Name: count, Length: 362, dtype: int64
os_1
 0.0000    413
 0.0002    398
 0.0004    394
-0.0005    390
 0.0001    382
          ...
-0.0075      1
 0.0087      1
-0.0087      1
-0.0078      1
 0.0077      1
Name: count, Length: 158, dtype: int64
os_2
-0.0003    2104
 0.0001    2097
 0.0000    2070
 0.0003    2065
-0.0004    2050
-0.0002    2049
 0.0002    2038
-0.0001    2029
 0.0004    1997
 0.0005    1068
-0.0005     958
 0.0006      71
-0.0006      34
Name: count, dtype: int64
os_3
100.0    20630
Name: count, dtype: int64
s_1
518.67    20630
Name: count, dtype: int64
s_2
642.50    190
642.56    189
642.53    188
642.60    184
642.67    179
         ...
641.21      1
644.31      1
644.34      1
644.22      1
644.39      1
Name: count, Length: 310, dtype: int64
s_3
1590.10    27
1589.76    26
1592.11    25
1589.98    25
1587.86    24
           ..
1577.66     1
1576.70     1
1577.12     1
1616.91     1
1610.87     1
Name: count, Length: 3012, dtype: int64
s_4
1409.01    20
1407.15    18
1407.02    18
1414.03    18
1404.47    18
           ..
1425.32     1
1428.93     1
1431.90     1
1433.58     1
1432.14     1
Name: count, Length: 4051, dtype: int64
s_5
14.62    20630
Name: count, dtype: int64
s_6
21.61    20224
21.60      406
Name: count, dtype: int64
s_7
553.62    116
553.76    115
553.94    110
553.72    110
553.43    108
         ...
550.91      1
550.62      1
550.52      1
555.64      1
550.79      1
Name: count, Length: 513, dtype: int64
s_8
2388.11    1181
2388.10    1159
2388.09    1149
2388.08    1126
2388.07    1077
2388.12    1069
2388.06    1049
2388.13    1033
2388.05    1013
2388.04     910
2388.14     881
2388.03     879
2388.02     812
2388.15     809
2388.01     754
2388.16     680
2388.17     567
2388.00     544
2388.18     479
2387.99     426
2388.19     393
2387.98     339
2388.20     318
2388.21     253
2388.22     227
2388.23     210
2387.97     201
2388.24     147
2387.96     145
2388.25     137
2388.26     121
2388.27      92
2388.28      87
2388.29      72
2387.95      72
2388.30      50
2388.31      37
2388.32      34
2387.94      33
2387.93      16
2388.33      13
2388.34      13
2387.92       9
2387.91       3
2388.35       2
2388.44       2
2388.50       1
2388.36       1
2388.37       1
2387.90       1
2388.52       1
2388.46       1
2388.56       1
Name: count, dtype: int64
s_9
9058.88    16
9060.55    15
9056.86    15
9060.87    15
9060.37    15
           ..
9071.66     1
9074.30     1
9078.12     1
9073.98     1
9071.43     1
Name: count, Length: 6403, dtype: int64
s_10
1.3    20630
Name: count, dtype: int64
s_11
47.46    341
47.57    338
47.49    332
47.45    332
47.47    330
        ...
46.90      1
46.91      1
48.43      1
46.85      1
48.48      1
Name: count, Length: 159, dtype: int64
s_12
521.63    143
521.42    136
521.35    131
521.56    129
521.54    125
         ...
519.39      1
519.13      1
519.27      1
519.14      1
519.18      1
Name: count, Length: 427, dtype: int64
s_13
2388.10    1164
2388.09    1144
2388.08    1129
2388.11    1127
2388.07    1112
2388.12    1099
2388.06    1005
2388.05     987
2388.13     976
2388.04     952
2388.14     914
2388.03     855
2388.15     817
2388.02     789
2388.01     699
2388.16     665
2388.00     573
2388.17     558
2388.18     443
2387.99     440
2388.19     387
2387.98     352
2388.20     330
2388.21     258
2388.22     231
2388.23     221
2387.97     219
2387.96     170
2388.24     160
2388.25     137
2388.26     121
2388.27     102
2387.95      95
2388.28      89
2388.29      61
2387.94      54
2388.30      44
2388.31      33
2388.32      29
2388.33      22
2387.93      19
2387.92      12
2388.34       8
2388.35       7
2388.36       6
2388.37       3
2388.39       2
2387.91       2
2387.89       1
2387.88       1
2388.44       1
2388.56       1
2388.55       1
2388.49       1
2388.54       1
2387.90       1
Name: count, dtype: int64
s_14
8138.89    17
8141.85    17
8136.89    16
8140.79    15
8136.69    15
           ..
8257.38     1
8270.91     1
8263.63     1
8147.98     1
8149.90     1
Name: count, Length: 6078, dtype: int64
s_15
8.4309    38
8.4318    37
8.4468    36
8.4442    35
8.4128    34
          ..
8.5592     1
8.5425     1
8.5518     1
8.5646     1
8.5389     1
Name: count, Length: 1918, dtype: int64
s_16
0.03    20630
Name: count, dtype: int64
s_17
393    5445
392    4577
394    4063
395    2339
391    2022
396    1185
390     452
397     436
398      72
389      30
399       7
388       1
400       1
Name: count, dtype: int64
s_18
2388    20630
Name: count, dtype: int64
s_19
100.0    20630
Name: count, dtype: int64
s_20
38.86    485
38.89    476
38.82    472
38.87    460
38.85    458
        ...
39.41      1
38.20      1
38.19      1
38.21      1
38.14      1
Name: count, Length: 120, dtype: int64
s_21
23.3222    23
23.3029    17
23.3725    16
23.2896    16
23.3497    15
           ..
23.0591     1
23.1218     1
23.0230     1
22.9735     1
22.9333     1
Name: count, Length: 4745, dtype: int64

In [19]:
# sns.heatmap(data=df.corr(),cmap="coolwarm",annot=True)
# sns.show()

df.corr()

,unit_number,time_in_cycles,os_1,os_2,os_3,s_1,s_2,s_3,s_4,s_5,...,s_12,s_13,s_14,s_15,s_16,s_17,s_18,s_19,s_20,s_21
unit_number,1.000000,0.078632,-0.017923,-0.006312,NaN,NaN,0.013991,0.012611,0.026041,NaN,...,-0.031857,0.044146,-0.059500,0.022438,NaN,0.013449,NaN,NaN,-0.020478,-0.016367
time_in_cycles,0.078632,1.000000,-0.004551,0.016030,NaN,NaN,0.549840,0.543969,0.624557,NaN,...,-0.611366,0.477484,0.370326,0.588670,NaN,0.566978,NaN,NaN,-0.583555,-0.585888
os_1,-0.017923,-0.004551,1.000000,0.011640,NaN,NaN,0.009004,-0.005653,0.009530,NaN,...,-0.001486,0.002302,-0.004474,0.007643,NaN,0.002587,NaN,NaN,-0.005692,-0.014541
os_2,-0.006312,0.016030,0.011640,1.000000,NaN,NaN,0.007152,0.009059,0.014612,NaN,...,-0.010901,0.018087,-0.006329,0.014117,NaN,0.012229,NaN,NaN,-0.010465,-0.007767
os_3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
s_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
s_2,0.013991,0.549840,0.009004,0.007152,NaN,NaN,1.000000,0.602642,0.714938,NaN,...,-0.724605,0.661770,0.179743,0.675979,NaN,0.629875,NaN,NaN,-0.661805,-0.668022
s_3,0.012611,0.543969,-0.005653,0.009059,NaN,NaN,0.602642,1.000000,0.678421,NaN,...,-0.680307,0.600973,0.237136,0.639923,NaN,0.600021,NaN,NaN,-0.625961,-0.633915
s_4,0.026041,0.624557,0.009530,0.014612,NaN,NaN,0.714938,0.678421,1.000000,NaN,...,-0.815595,0.745147,0.190740,0.758454,NaN,0.703489,NaN,NaN,-0.748055,-0.745181
s_5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
s_6,0.026445,0.105997,-0.001338,0.014365,NaN,NaN,0.132264,0.116040,0.150490,NaN,...,-0.155887,0.158288,-0.002110,0.149047,NaN,0.130817,NaN,NaN,-0.141434,-0.137432
s_7,-0.031982,-0.595882,-0.009420,-0.016605,NaN,NaN,-0.702115,-0.664609,-0.793120,NaN,...,0.812721,-0.764598,-0.110042,-0.747048,NaN,-0.692882,NaN,NaN,0.736145,0.737430
s_8,0.039889,0.475969,-0.000435,0.013251,NaN,NaN,0.662334,0.602481,0.746849,NaN,...,-0.786538,0.826086,-0.144795,0.700945,NaN,0.627779,NaN,NaN,-0.687031,-0.688838
s_9,-0.052130,0.443968,-0.004292,-0.005483,NaN,NaN,0.273717,0.322965,0.297401,NaN,...,-0.210229,-0.034808,0.963164,0.293736,NaN,0.337088,NaN,NaN,-0.285241,-0.292761
s_10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
s_11,0.024687,0.634403,0.011654,0.011673,NaN,NaN,0.740052,0.695900,0.830142,NaN,...,-0.846883,0.780770,0.163405,0.780913,NaN,0.722298,NaN,NaN,-0.771528,-0.772567
s_12,-0.031857,-0.611366,-0.001486,-0.010901,NaN,NaN,-0.724605,-0.680307,-0.815595,NaN,...,1.000000,-0.788448,-0.098137,-0.766051,NaN,-0.703485,NaN,NaN,0.751956,0.756271
s_13,0.044146,0.477484,0.002302,0.018087,NaN,NaN,0.661770,0.600973,0.745147,NaN,...,-0.788448,1.000000,-0.147054,0.697656,NaN,0.627396,NaN,NaN,-0.686152,-0.688929
s_14,-0.059500,0.370326,-0.004474,-0.006329,NaN,NaN,0.179743,0.237136,0.190740,NaN,...,-0.098137,-0.147054,1.000000,0.193755,NaN,0.246615,NaN,NaN,-0.187355,-0.192406
s_15,0.022438,0.588670,0.007643,0.014117,NaN,NaN,0.675979,0.639923,0.758454,NaN,...,-0.766051,0.697656,0.193755,1.000000,NaN,0.669198,NaN,NaN,-0.707669,-0.704038
s_16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
s_17,0.013449,0.566978,0.002587,0.012229,NaN,NaN,0.629875,0.600021,0.703489,NaN,...,-0.703485,0.627396,0.246615,0.669198,NaN,1.000000,NaN,NaN,-0.651008,-0.658697
s_18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
s_19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
s_20,-0.020478,-0.583555,-0.005692,-0.010465,NaN,NaN,-0.661805,-0.625961,-0.748055,NaN,...,0.751956,-0.686152,-0.187355,-0.707669,NaN,-0.651008,NaN,NaN,1.000000,0.693456
s_21,-0.016367,-0.585888,-0.014541,-0.007767,NaN,NaN,-0.668022,-0.633915,-0.745181,NaN,...,0.756271,-0.688929,-0.192406,-0.704038,NaN,-0.658697,NaN,NaN,0.693456,1.000000